Automatically bump Forge compat base image to latest release

diff --git a/.github/workflows/docker-build-test.yaml b/.github/workflows/docker-build-test.yaml
--- a/.github/workflows/docker-build-test.yaml
+++ b/.github/workflows/docker-build-test.yaml
@@ -307,17 +307,51 @@ jobs:
         github.event.pull_request.auto_merge != null ||
         contains(github.event.pull_request.body, '#e2e')
       )
-    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-forge.yaml@main
-    secrets: inherit
-    with:
-      GIT_SHA: ${{ needs.determine-docker-build-metadata.outputs.gitSha }}
-      FORGE_TEST_SUITE: compat
-      IMAGE_TAG: 25a081116546670e62ca927ba90478de78557056 #aptos-node-v1.20
-      FORGE_RUNNER_DURATION_SECS: 300
-      COMMENT_HEADER: forge-compat
-      FORGE_NAMESPACE: forge-compat-${{ needs.determine-docker-build-metadata.outputs.targetCacheId }}
-      SKIP_JOB: ${{ needs.file_change_determinator.outputs.only_docs_changed == 'true' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Fetch all history for all branches and tags
+      - name: Determine branch to fetch latest docker image tag from
+        id: determine-the-target-branch-to-fetch-the-latest-docker-image-tag-from
+        # To test the compat test against the last released docker image, we need to get the last released docker image tag.
+        # This step determines appropriate branch to fetch the latest docker image tag from based on the current branch.
+        # Determine the IMAGE_TAG based on the latest release R and check for images built on branch R - 1:
+        #   - For commits on the `aptos-release-v1.19` branch, the `IMAGE_TAG` should be the latest commit built on `aptos-release-v1.18`
+        #   - For commits on the `main` branch, the `IMAGE_TAG` should be the latest commit on the max release `aptos-release-v<MAX>` branch
+        run: |
+          current_branch="${{ github.ref_name }}"
+          if [[ $current_branch == "main" ]]; then
+            # Find the latest release branch
+            target_branch=$(git ls-remote --heads origin 'aptos-release-v*' | sort -V | tail -n 1 | awk -F'/' '{print $NF}')
+          elif [[ $current_branch =~ ^aptos-release-v([0-9]+)\.([0-9]+)$ ]]; then
+            major=${BASH_REMATCH[1]}
+            minor=${BASH_REMATCH[2]}
+            prev_minor=$((minor - 1))
+            target_branch="aptos-release-v${major}.${prev_minor}"
+          else
+            echo "Error: Unsupported branch format" >&2
+            exit 1
+          fi
+          echo "TARGET_BRANCH=${target_branch}" >> $GITHUB_OUTPUT
 
+      - uses: aptos-labs/aptos-core/.github/actions/get-latest-docker-image-tag@main
+        id: get-docker-image-tag
+        with:
+          branch: ${{ steps.determine-the-target-branch-to-fetch-the-latest-docker-image-tag-from.outputs.TARGET_BRANCH }}
+          variants: "failpoints performance"
+
+      - uses: ./.github/workflows/workflow-run-forge.yaml@main
+        with:
+          GIT_SHA: ${{ needs.determine-docker-build-metadata.outputs.gitSha }}
+          FORGE_TEST_SUITE: compat
+          IMAGE_TAG: ${{ steps.get-docker-image-tag.outputs.IMAGE_TAG }}
+          FORGE_RUNNER_DURATION_SECS: 300
+          COMMENT_HEADER: forge-compat
+          FORGE_NAMESPACE: forge-compat-${{ needs.determine-docker-build-metadata.outputs.targetCacheId }}
+          SKIP_JOB: ${{ needs.file_change_determinator.outputs.only_docs_changed == 'true' }}
+  
   # Run forge framework upgradability test. This is a PR required job.
   forge-framework-upgrade-test:
     needs:
